# Generated by Django 3.0.3 on 2020-02-23 22:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BlogApp.Category'),
            preserve_default=False,
        ),
    ]
