# Generated by Django 3.0.3 on 2020-02-25 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_post_postcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postSlug',
        ),
    ]
